



<?php if($erreur):?><p><?=$erreur;?></p><?php endif;?>
<?php if($user):?><p><?=$user;?></p><?php endif;?>



<form action="addUser.php" method="POST">


    <label for="name">nom</label>
    <input type="text" name="name" id="name" value="<?= $data['name'];?>">

    <label for="firstName">prenom</label>
    <input type="text" name="firstName" id="firstName" value="<?= $data['firstName'];?>">

    <label for="mail">email</label>
    <input type="text" name="mail" id="mail" value="<?= $data['mail'];?>">

    <label for="password">password</label>
    <input type="password" name="password" id="password" value="<?= $data['password'];?>">

    <label for="password2">password</label>
    <input type="password" name="password2" id="password2" value="<?= $data['password2'];?>">

    <label for="pseudo">pseudo</label>
    <input type="text" name="pseudo" id="pseudo" value="<?= $data['pseudo'];?>">

    <label for="role">role</label>
    <input type="text" name="role" id="role" value="<?= $data['role'];?>">

    <input type="submit" value="ajouter">

</form>